version: '3'

services:
  siproad-products-api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMG_NAME}
    container_name: ${DOCKER_APP_CONTAINER_NAME}
    restart: always
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    env_file:
      - .env